title: Better Cayman Jekyll Theme
email: morpheus636@morpheus636.com
description: "Better Cayman is a simple theme for Jekyll"

# Build settings
markdown: kramdown
remote_theme: Morpheus636/better-cayman
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

include_maintained_by: false
